name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Multi-Platform Docker Image
      uses: docker/build-push-action@v6
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ github.repository_owner }}/ebusd-custom:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ebusd-custom:latest
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ebusd-custom:latest,mode=max
